### PR TITLE
add nltk stemming

### PR DESCRIPTION
**Pull request by jcrowgey**
@adiel-mittmann Found your fork (after all this time :+1:).  I'm thinking about working on neolo a bit more and so I thought I'd pull your changes.  Did this nltk patch work out for you?

### CODE REVIEW

**Comment by NUPLID** [comment]
There is bug I noticed yesterday and need help to solve it, pls.. In the list of 'Wordtypes and frequencies (unigram model):' the question marks (?) and exclamation marks (!) do not appear and thus the 'calculation of sentences in your text.', 'Average sentence length:'and 'Punctuation ratio:' results are coming wrong. Tks.

**Comment by adiel-mittmann** [comment]
I can confirm that it's working here.

**Comment by jcrowgey** [comment]
Awesome, thanks.  I'll merge it then.  I'll probably do some work to integrate the dependency on nltk as optional, but I appreciate the contribution.

**Comment by jcrowgey** [comment]
Merged your commits into the past with some git-fu.  Closing this PR since the work is merged.  Thanks!

**Pull request closed without merging**
